<?php

/**
 * @file
 * Primary module hooks for Simple Github Manager module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_theme().
 */
function simple_github_manager_theme() {
  return [
    'simple_github_manager' => [
      'variables' => [
        'url_parent' => '',
        'git_repo_arr' => [],
        'my_form' => NULL,
      ],
      'render element' => 'form'
    ],
  ];
}

///**
// * Prepares variables for simple-github-manager template.
// *
// * Default template: simple-github-manager.html.twig.
// *
// * @param array $variables
// *   An associative array containing:
// *   - foo: Foo variable description.
// */
//function template_preprocess_simple_github_manager(array &$variables) {
//  $variables['foo'] = 'bar';
//}


//function yourmodule_element_info_alter(array &$types) {
//  if (isset($types['table'])) {
//    $types['table']['#attached']['library'][] = 'your_module/library_name';
//  }
//}
